import type { Language } from './language';

export const commonCopy = {
  th: { selectLanguage: 'เลือกภาษา', myLearning: 'การเรียนของฉัน', all: 'ทั้งหมด', search: 'ค้นหารายวิชา', studentAccount: 'บัญชีนักเรียน', teacherAccount: 'บัญชีผู้สอน', approverAccount: 'บัญชีผู้อนุมัติ', ownerAccount: 'บัญชีผู้บริหาร', logout: 'ออกจากระบบ', logoutHint: 'สิ้นสุดเซสชันในเบราว์เซอร์นี้', account: 'บัญชี Institute X', checking: 'กำลังตรวจสอบเซสชัน', loading: 'กำลังโหลดข้อมูล Institute X', connecting: 'กำลังเชื่อมต่อ Backend API…', loadError: 'ไม่สามารถโหลดหน้านี้ได้', retryHint: 'ตรวจสอบว่า Backend ทำงานอยู่ แล้วรีเฟรชหน้าอีกครั้ง' },
  en: { selectLanguage: 'Select language', myLearning: 'My learning', all: 'All', search: 'Search courses', studentAccount: 'Student account', teacherAccount: 'Teacher account', approverAccount: 'Approver account', ownerAccount: 'Executive account', logout: 'Log out', logoutHint: 'End this browser session', account: 'Institute X account', checking: 'Checking your session', loading: 'Loading Institute X data', connecting: 'Connecting to the backend API…', loadError: 'Unable to load this page', retryHint: 'Check that the backend is running and then refresh the page.' },
  'zh-CN': { selectLanguage: '选择语言', myLearning: '我的学习', all: '全部', search: '搜索课程', studentAccount: '学生账户', teacherAccount: '教师账户', approverAccount: '审批者账户', ownerAccount: '管理者账户', logout: '退出登录', logoutHint: '结束此浏览器会话', account: 'Institute X 账户', checking: '正在检查会话', loading: '正在加载 Institute X 数据', connecting: '正在连接后端 API…', loadError: '无法加载此页面', retryHint: '请检查后端是否正在运行，然后刷新页面。' },
  ja: { selectLanguage: '言語を選択', myLearning: 'マイラーニング', all: 'すべて', search: 'コースを検索', studentAccount: '学生アカウント', teacherAccount: '教師アカウント', approverAccount: '承認者アカウント', ownerAccount: 'エグゼクティブアカウント', logout: 'ログアウト', logoutHint: 'このブラウザーセッションを終了します', account: 'Institute X アカウント', checking: 'セッションを確認しています', loading: 'Institute X のデータを読み込み中', connecting: 'バックエンド API に接続しています…', loadError: 'このページを読み込めません', retryHint: 'バックエンドが実行中か確認して、ページを更新してください。' },
} as const satisfies Record<Language, Record<string, string>>;

export const shellCopy = {
  th: { overview: 'ภาพรวม', courses: 'รายวิชาของฉัน', allCourses: 'รายวิชาทั้งหมด', permission: 'สิทธิ์การสอน', teacherWorkspace: 'พื้นที่ผู้สอน', courseAuthoring: 'การสร้างรายวิชา', reviewOverview: 'ภาพรวมการตรวจสอบ', teacherRequests: 'คำขอของผู้สอน', courseReviews: 'ตรวจสอบรายวิชา', courseReports: 'รายงานรายวิชา', approverWorkspace: 'พื้นที่ผู้อนุมัติ', approvalOperations: 'งานอนุมัติ', systemOverview: 'ภาพรวมระบบ', users: 'ผู้ใช้', operations: 'การดำเนินงาน', ownerWorkspace: 'พื้นที่ผู้บริหาร', systemOversight: 'การกำกับดูแลระบบ' },
  en: { overview: 'Overview', courses: 'My courses', allCourses: 'All courses', permission: 'Teaching permission', teacherWorkspace: 'Teacher workspace', courseAuthoring: 'Course authoring', reviewOverview: 'Review overview', teacherRequests: 'Teacher requests', courseReviews: 'Course reviews', courseReports: 'Course reports', approverWorkspace: 'Approver workspace', approvalOperations: 'Approval operations', systemOverview: 'System overview', users: 'Users', operations: 'Operations', ownerWorkspace: 'Executive workspace', systemOversight: 'System oversight' },
  'zh-CN': { overview: '概览', courses: '我的课程', allCourses: '所有课程', permission: '教学权限', teacherWorkspace: '教师工作区', courseAuthoring: '课程创作', reviewOverview: '审核概览', teacherRequests: '教师申请', courseReviews: '课程审核', courseReports: '课程举报', approverWorkspace: '审批工作区', approvalOperations: '审批操作', systemOverview: '系统概览', users: '用户', operations: '运行状况', ownerWorkspace: '管理者工作区', systemOversight: '系统监管' },
  ja: { overview: '概要', courses: 'マイコース', allCourses: 'すべてのコース', permission: '教育権限', teacherWorkspace: '教師ワークスペース', courseAuthoring: 'コース作成', reviewOverview: 'レビュー概要', teacherRequests: '教師リクエスト', courseReviews: 'コースレビュー', courseReports: 'コースの報告', approverWorkspace: '承認ワークスペース', approvalOperations: '承認業務', systemOverview: 'システム概要', users: 'ユーザー', operations: '運用状況', ownerWorkspace: 'エグゼクティブワークスペース', systemOversight: 'システム監視' },
} as const satisfies Record<Language, Record<string, string>>;
